services:
    postgres:
        image: postgres:latest
        container_name: postgresql
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - ./data:/var/lib/volume/postgresql/data
